/* Model Controller / Insert_Stack

   Created : 2011-04-11
   Last Modified : 2011-04-11
   Author : Tom Coleman
   Copyright : 2011-2011
   By : University of Mississippi Medical Center */

using System ;
using System.Collections ;
using System.Drawing ;
using System.Windows.Forms ;

namespace ModelEditor
{ public class Insert_Stack
  { public static Stack TreeStack = new Stack (10) ;
  }
}

/* End */
