/* Model Editor / TabData

   Created : 2011-04-07
   Last Modified : 2011-04-11
   Author : Tom Coleman
   Copyright : 2011-2011
   By : University of Mississippi Medical Center */

using System ;
using System.Collections ;
using System.Drawing ;
using System.Windows.Forms ;

namespace ModelEditor
{ public class TabData
  { public String Filename ;
    public RichTextBox Box ;
  }
}

/* End */
